### ISSUE TITLE
Simiplify .pmtype options for make_pmtable

### ISSUE THREAD

**Issue by kylebaron** [metrumresearchgroup/pmparams#38]
- Drop `fixed and random` 
- Simplify the labels for `fixed structural` (to `structural`) and `fixed covariate` (to `covariate`)

**Comment by KatherineKayMRG** [comment]
@graceannobrien we weren't clear what the difference was between `fixed and random` and `full`. 

I'm not sure where to request this but can we please update the user help for this function - right now there is a list of options but it would be helpful to know what each option gets you, e.g., 

- full: all rows in .df retained in pmtable
- fixed: all rows with type = "Struct" or "effect"
- structural: all rows with type = "Struct"
- covariate: all rows with type = "effect"
- random:  all rows with greek = "Omega" and type = "Resid"

Also, should we make that `greek = "Omega"` option check for `omega` or `Omega`?

**Comment by graceannobrien** [comment]
@KatherineKayMRG if users does `define_param_table` and `format_param_table` prior to this, it's not possible for `Omega` to not have capital `O`

**Comment by graceannobrien** [comment]
@KatherineKayMRG for random, you wrote:
random: all rows with greek = "Omega" **and** type = "Resid"
But in code, it is:
greek="Omega" **or** type = "Resid"

**Comment by KatherineKayMRG** [comment]
> @KatherineKayMRG for random, you wrote: random: all rows with greek = "Omega" **and** type = "Resid" But in code, it is: greek="Omega" **or** type = "Resid"

Sorry, you're right. I was thinking it includes both cases but you're right that it maybe clearer for this to match the code and say **or**
