### ISSUE TITLE
customising IIV table - PAGE MERGE workshop 250624

### ISSUE THREAD

**Issue by LeoLuongVuong** [metrumresearchgroup/pmparams#57]
# Summary

As a user, I was wondering if there is a way to customise the IIV table with pmtables package? I.e. specifying where "CV%" shows up in the IIV table. E.g. having CV% next to "IIV-x" term, instead of having it next to the value as the default.

Thanks.
Leo.

**Comment by kylebaron** [comment]
Hi @LeoLuongVuong  - 

Thanks for reaching out. The pmtables package is involved in general formatting and rendering of that table. The pmparams package is responsible for that sort of content and layout. 

I've transferred the issue here for consideration. 

Kyle

**Comment by LeoLuongVuong** [comment]
Thanks a lot for your help

Leo

**Comment by graceannobrien** [comment]
Hi @LeoLuongVuong ,
We do not have any plans to incorporate this functionality at present, but you can obtain your desired display by doing the following:

```
param_df <- sum %>% 
  define_param_table(.key = key) %>% 
  format_param_table(.select_cols = "all") %>% #select all columns so you can easily grab cv and corr_SD
#make desired edits to abb and value columns
  mutate(
    abb = case_when(
      cv != "-" ~ paste0(abb, " [CV\\%=", cv, "]"), 
      corr_SD != "-" ~ paste0(abb, " [Corr=", corr_SD, "]"), 
      TRUE ~ abb),
    value = gsub( " .*$", "", value)
  )

param_df %>% 
  make_pmtable(.pmtype = "random") %>% 
  stable() %>% 
  st2report()
```
Pleas let us know if you have any additional questions!

**Comment by LeoLuongVuong** [comment]
Perfect! It's great to know that there's a solution for it.
I first knew about pmparams when I took the course given by Metrum last month in Rome.
I am planning to implement the tools learnt (e.g. pmtable, bbr, etc.) into my daily workflow, so I will definitely have more questions in the future!

Many thanks.
