### ISSUE TITLE
Options for random effects when additive in log domain

### ISSUE THREAD

**Issue by graceannobrien** [metrumresearchgroup/pmparams#6]
Methods will be same as proportional error term outside the log domain

**Comment by timwaterhouse** [comment]
Minor clarification: `sqrt(exp(sigma) - 1) * 100`

**Comment by graceannobrien** [comment]
Add `addErrLogDV` as option in trans. Will also need to update example parameter key to include this option. 

"addErrLogDV" - for additive error log terms (coded using SIGMA in $ERROR) -returns est.+ SD

```
if (trans = "addErrlogDV"){
    sqrt(exp(sigma) - 1) * 100)
}
```
